repos:
  - repo: local
    hooks:
      - id: auto-debug-repair
        name: Auto Debug Repair
        entry: python auto_debug_repair.py
        language: system
        files: \.py$
        stages: [manual]
        pass_filenames: false
        always_run: true

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: ^\.auto_debug_state\.json$   # do not touch the repair state file
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        exclude: ^(backup|old|archive|tmp|\.?venv|\.mypy_cache|\.pytest_cache|dist|build)(/|\\)

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        exclude: ^(backup|old|archive|tmp|\.?venv|\.mypy_cache|\.pytest_cache|dist|build)(/|\\)

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-docstrings
          - flake8-bugbear
          - flake8-comprehensions
        exclude: ^(backup|old|archive|tmp|\.?venv|\.mypy_cache|\.pytest_cache|dist|build)(/|\\)
        # If you want to temporarily silence package docstring errors, uncomment:
        # args: ["--extend-ignore=D104"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
      - id: mypy
        additional_dependencies: []
        exclude: ^(backup|old|archive|tmp|\.?venv|\.mypy_cache|\.pytest_cache|dist|build)(/|\\)
