name: Streamlit App

on:
  push:
    branches:
      - stage

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run backfill script
        run: |
          mkdir -p data/daily
          python backfill_all_symbols.py
        env:
<<<<<<< HEAD
          POLYGON_API_KEY: ${{ secrets.POLYGON_API_KEY }}
=======
          POLYGON_API_KEY: ${{ secrets.POLYGON_API_KEY }}
>>>>>>> d982fc6be90420afd57756f125f15b445325fe38
