name: Streamlit App CI  # Name of your workflow

on:  # Triggers: Run on pushes and pull requests to the main branch
  push:
    branches: [main]  # Change 'main' if your default branch is different (e.g., 'master')
  pull_request:
    branches: [main]

jobs:
  test:  # Job name
    runs-on: ubuntu-latest  # Use Linux environment (matches Streamlit Cloud)

    steps:
      - name: Checkout code  # Step 1: Clone your repo
        uses: actions/checkout@v4

      - name: Set up Python  # Step 2: Set up Python (match Streamlit Cloud's version)
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'  # Use 3.13 to match your error environment; change to '3.12' if testing alternatives

      - name: Install dependencies  # Step 3: Install from requirements.txt
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ruff  # For linting (if not in requirements.txt)

      - name: Lint with Ruff  # Step 4: Lint all Python files for syntax/style issues
        run: ruff check .

      - name: Test with Streamlit App Action  # Step 5: Run Streamlit's smoke tests
        uses: streamlit/streamlit-app-action@v0.0.3
        with:
          app-path: app.py  # Replace with your main app file (e.g., home.py or main.py)
