name: Streamlit App

on:
  push:
    branches:
      - stage

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run backfill with delay
        run: |
          for i in {1..10}; do
            python backfill_all_symbols.py
            sleep 60  # 1-minute delay between runs
            if [ $? -eq 0 ]; then break; fi
          done
        env:
          POLYGON_API_KEY: ${{ secrets.POLYGON_API_KEY }}
